version: '3.8'

services:
  mysql-container:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: datab
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root  # Optional, for root access
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app-container:
    build: .  # Build the image from the current directory (.)
    depends_on:
      - mysql-container  # Ensure MySQL starts before Spring Boot app
    environment:
      # Define your database connection details here (replace placeholders)
      DB_HOST: mysql-container
      DB_PORT: 3306
      DB_NAME: datab
      DB_USER: user
      DB_PASSWORD: pass
    ports:
      - "8080:8080"  # Expose your Spring Boot app port

volumes:
  mysql-data: {}